server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Fix for Firebase Auth signInWithPopup
    add_header Cross-Origin-Opener-Policy same-origin-allow-popups;
    add_header Cross-Origin-Embedder-Policy unsafe-none;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
