import { db } from "../../firebaseInit.js";
import { logger } from "../../lib/utils.js";
export const handleApp = async (req, res) => {
    const path = req.path;
    const baseUrl = 'https://dreambeesai.com';
    let title = "AI Image Generator - Text to Image Online";
    let desc = "Generate high-quality AI art directly on the web. No Discord required. Fast, private, and powerful text-to-image creation.";
    let image = `${baseUrl}/dreambees_icon.png`;
    const structuredData = [];
    let statusCode = 200;
    const canonicalUrl = `${baseUrl}${path}`;
    // Skeleton Content
    let skeletonH1 = "DreamBeesAI: Professional AI Art Creation";
    let skeletonP = "Join the next generation of digital artists. Create stunning AI characters, models, and concepts in seconds directly in your browser.";
    try {
        // 1. DISCOVERY / IMAGES
        if (path.startsWith('/discovery/')) {
            const rawId = path.split('/').pop();
            const id = (rawId && rawId.includes('-')) ? rawId.split('-').pop() : rawId;
            if (id && id !== 'discovery') {
                let docSnap = await db.collection('model_showcase_images').doc(id).get();
                if (!docSnap.exists) {
                    docSnap = await db.collection('generations').doc(id).get();
                }
                if (docSnap.exists) {
                    const data = docSnap.data();
                    const prompt = data.prompt || "AI Artwork";
                    title = `${prompt.slice(0, 60)}... | DreamBeesAI`;
                    desc = `Full details and prompt for this AI generation: "${prompt.slice(0, 150)}"`;
                    image = data.thumbnailUrl || data.url || data.imageUrl || image;
                    skeletonH1 = prompt;
                    skeletonP = `A beautiful AI generation created with DreamBeesAI. Model used: ${data.modelId || 'Stable Diffusion'}.`;
                    structuredData.push({
                        "@context": "https://schema.org",
                        "@type": "VisualArtwork",
                        "name": prompt.slice(0, 100),
                        "image": image,
                        "creator": { "@type": "Person", "name": data.userDisplayName || "AI Creator" }
                    });
                    structuredData.push({
                        "@context": "https://schema.org",
                        "@type": "BreadcrumbList",
                        "itemListElement": [
                            { "@type": "ListItem", "position": 1, "name": "Home", "item": baseUrl },
                            { "@type": "ListItem", "position": 2, "name": "Discovery", "item": `${baseUrl}/discovery` },
                            { "@type": "ListItem", "position": 3, "name": prompt.slice(0, 20), "item": canonicalUrl }
                        ]
                    });
                }
                else {
                    statusCode = 404;
                }
            }
            else {
                title = "Discover AI Generated Art | DreamBeesAI";
                desc = "Explore the best AI art generated by the DreamBees community. Photorealistic, anime, and 3D concept art.";
            }
        }
        // 2. BLOG
        else if (path.startsWith('/blog/')) {
            const id = path.split('/').pop();
            if (id === 'prompt-director-drift-evaluation') {
                title = "Prompt Director Drift Evaluation | DreamBeesAI";
                desc = "Evaluating the impact of prompt director models on image variance and quality.";
                skeletonH1 = "Blog: Prompt Director Drift Evaluation";
            }
            else if (id === 'elon-musk-docket-case') {
                title = "OpenAI vs Elon Musk: Analysis | DreamBeesAI";
                desc = "Analyzing the legal and governance implications of the OpenAI vs Elon Musk docket.";
                skeletonH1 = "Blog: OpenAI vs Elon Musk";
                image = `${baseUrl}/assets/blog/openai_vs_elon_musk.png`;
            }
            else if (id && id !== 'blog') {
                statusCode = 404;
            }
            else {
                title = "AI Art & Technology Blog | DreamBeesAI";
                desc = "Insights into stable diffusion, cloud rendering, and the future of AI art creation.";
            }
        }
        // 3. MODELS
        else if (path.startsWith('/model/')) {
            const id = path.split('/').pop();
            if (id && id !== 'model') {
                const modelSnap = await db.collection('models').doc(id).get();
                if (modelSnap.exists) {
                    const data = modelSnap.data();
                    title = `${data.name} AI Model - DreamBeesAI`;
                    desc = data.description || `Instagram-style showcase feed for the ${data.name} AI model. High-quality trained weights for niche styles.`;
                    image = data.image || image;
                    skeletonH1 = `${data.name} AI Model Showcase`;
                    skeletonP = data.description || `Exlpore what's possible with the ${data.name} model on DreamBeesAI.`;
                    structuredData.push({
                        "@context": "https://schema.org",
                        "@type": "BreadcrumbList",
                        "itemListElement": [
                            { "@type": "ListItem", "position": 1, "name": "Home", "item": baseUrl },
                            { "@type": "ListItem", "position": 2, "name": "Models", "item": `${baseUrl}/models` },
                            { "@type": "ListItem", "position": 3, "name": data.name, "item": canonicalUrl }
                        ]
                    });
                }
                else {
                    statusCode = 404;
                }
            }
        }
        // 4. LANDING / SPECIAL PAGES
        else if (path === '/verify') {
            title = "Pair Discord Account | DreamBeesAI";
            desc = "Securely pair your Discord account and start generating art with DreamBees.";
            skeletonH1 = "Pair Discord Account";
            skeletonP = "Please confirm the link between your Discord and DreamBees identity to enable Discord commands.";
        }
        else if (path === '/landing' || path === '/') {
            structuredData.push({
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "DreamBeesAI",
                "applicationCategory": "DesignApplication",
                "operatingSystem": "Web",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.9", "ratingCount": "1240" },
                "description": desc
            });
        }
        const metaTags = `
  <title>${title}</title>
  <meta name="description" content="${desc}" />
  <link rel="canonical" href="${canonicalUrl}" />
  <meta property="og:site_name" content="DreamBeesAI" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="${title}" />
  <meta property="og:description" content="${desc}" />
  <meta property="og:image" content="${image.startsWith('http') ? image : baseUrl + image}" />
  <meta property="og:url" content="${baseUrl}${path}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${title}" />
  <meta name="twitter:description" content="${desc}" />
  <meta name="twitter:image" content="${image.startsWith('http') ? image : baseUrl + image}" />
  ${structuredData.length > 0 ? structuredData.map(sd => `<script type="application/ld+json">${JSON.stringify(sd)}</script>`).join('\n') : ''}
`;
        res.set('Cache-Control', 'public, max-age=3600, s-maxage=3600');
        res.status(statusCode).send(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    ${metaTags}
</head>
<body style="margin:0; background: #000; color: #fff;">
    <div id="root">
        <!-- SERVER-SIDE SKELETON FOR SEO -->
        <div style="padding: 2rem; max-width: 800px; margin: 0 auto; font-family: sans-serif; display: none; visibility: hidden;">
            <h1 style="color: #fff; font-size: 2.5rem; margin-bottom: 1rem;">${skeletonH1}</h1>
            <p style="color: #ccc; font-size: 1.25rem; line-height: 1.6;">${skeletonP}</p>
        </div>
    </div>
    <div id="loading-fallback" style="display: flex; align-items: center; justify-content: center; height: 100vh; font-family: sans-serif;">
        <p style="font-size: 1.2rem; letter-spacing: 0.1em; color: rgba(255,255,255,0.7);">ORCHESTRATING IMAGINATION...</p>
    </div>
    <script type="module" src="/src/main.jsx"></script>
</body>
</html>
        `);
    }
    catch (err) {
        logger.error("Error in serveApp:", err);
        res.status(500).send("Internal Server Error");
    }
};
//# sourceMappingURL=appHandler.js.map