import { db, FieldValue } from "../firebaseInit.js";
import { HttpsError } from "firebase-functions/v2/https";
import { RequestWithAuth } from "../types/functions.js";
import { logger } from "../lib/utils.js";
import { ensureUserExists } from "../lib/user.js";


export const handleLinkDiscordAccount = async (request: RequestWithAuth<{ token: string }>) => {
    const { uid } = request.auth;
    const { token } = request.data;

    if (!token) throw new HttpsError('invalid-argument', 'Token is required.');

    const tokenRef = db.collection('discord_pairing_tokens').doc(token);
    
    return await db.runTransaction(async (t) => {
        const tokenSnap = await t.get(tokenRef);
        if (!tokenSnap.exists) {
            throw new HttpsError('not-found', 'Invalid or expired pairing token.');
        }

        const tokenData = tokenSnap.data() as any;
        if (tokenData.expiresAt.toDate() < new Date()) {
            throw new HttpsError('failed-precondition', 'Pairing token has expired.');
        }

        const discordId = tokenData.discordId;
        const userRef = db.collection('users').doc(uid);

        // Update User
        t.update(userRef, {
            discordId: discordId,
            discordTag: tokenData.discordTag,
            discordLinkedAt: new Date()
        });

        // Delete Token
        t.delete(tokenRef);

        return { success: true, discordTag: tokenData.discordTag };
    });
}

export const handleRegisterDiscordGrid = async (request: RequestWithAuth<{
    gridUrl: string,
    prompt: string,
    modelId: string,
    targetUserId: string,
    targetDisplayName?: string,
    targetPhotoURL?: string,
    requestId: string
}>) => {
    // Only allow admin or system to register grids on behalf of users
    const callerRole = (request.auth as any).token?.role || 'user';
    if (!['admin', 'system'].includes(callerRole)) {
        throw new HttpsError('permission-denied', 'Only system can register Discord grids.');
    }

    const { gridUrl, prompt, modelId, targetUserId, targetDisplayName, targetPhotoURL, requestId } = request.data;
    if (!gridUrl || !targetUserId) {
        throw new HttpsError('invalid-argument', 'Missing gridUrl or targetUserId.');
    }

    // --- Hardening: Validate URL domain ---
    const { B2_PUBLIC_URL } = await import("../lib/constants.js");
    if (B2_PUBLIC_URL && !gridUrl.startsWith(B2_PUBLIC_URL)) {
        logger.error("[DiscordSync] Invalid gridUrl domain", new Error("URL validation failed"), { gridUrl });
        throw new HttpsError('invalid-argument', 'Invalid image domain.');
    }

    try {
        return await db.runTransaction(async (t) => {
            // --- JIT Provisioning within Transaction ---
            const userReady = await ensureUserExists(targetUserId, targetDisplayName, targetPhotoURL, t);
            if (!userReady) {
                throw new HttpsError('not-found', 'Failed to provision or verify target user.');
            }

            const imageRef = db.collection("images").doc();

            // 1. Add to images collection
            t.set(imageRef, {
                userId: targetUserId,
                prompt,
                modelId,
                imageUrl: gridUrl,
                thumbnailUrl: gridUrl,
                isPublic: true,
                createdAt: FieldValue.serverTimestamp(),
                originalRequestId: requestId,
                _type: 'discord_grid'
            });

            // 2. Add to user's bookmarks
            const bookmarkRef = db.collection("users").doc(targetUserId).collection("bookmarks").doc(imageRef.id);
            t.set(bookmarkRef, {
                imageId: imageRef.id,
                imageUrl: gridUrl,
                prompt,
                createdAt: FieldValue.serverTimestamp(),
                _autoGenerated: true,
                _type: 'discord_grid'
            });

            logger.info(`[DiscordSync] Registered grid: ${imageRef.id} for user: ${targetUserId}`);
            return { success: true, imageId: imageRef.id };
        });
    } catch (error: any) {
        if (error instanceof HttpsError) throw error;
        throw new HttpsError('internal', error.message);
    }
}

export const handleRegisterDiscordUpscale = async (request: RequestWithAuth<{
    imageUrl: string,
    prompt: string,
    modelId: string,
    targetUserId: string,
    targetDisplayName?: string,
    targetPhotoURL?: string,
    requestId: string,
    aspectRatio?: string
}>) => {
    const callerRole = (request.auth as any).token?.role || 'user';
    if (!['admin', 'system'].includes(callerRole)) {
        throw new HttpsError('permission-denied', 'Only system can register Discord upscales.');
    }

    const { imageUrl, prompt, modelId, targetUserId, targetDisplayName, targetPhotoURL, requestId, aspectRatio = '1:1' } = request.data;
    if (!imageUrl || !targetUserId) {
        throw new HttpsError('invalid-argument', 'Missing imageUrl or targetUserId.');
    }

    try {
        return await db.runTransaction(async (t) => {
            // --- JIT Provisioning within Transaction ---
            const userReady = await ensureUserExists(targetUserId, targetDisplayName, targetPhotoURL, t);
            if (!userReady) {
                throw new HttpsError('not-found', 'Failed to provision or verify target user.');
            }

            const imageRef = db.collection("images").doc();

            // 1. Add to images collection
            t.set(imageRef, {
                userId: targetUserId,
                prompt,
                modelId,
                imageUrl,
                thumbnailUrl: imageUrl,
                aspectRatio,
                isPublic: true,
                createdAt: FieldValue.serverTimestamp(),
                originalRequestId: requestId,
                _type: 'discord_upscale'
            });

            // 2. Add to user's bookmarks
            const bookmarkRef = db.collection("users").doc(targetUserId).collection("bookmarks").doc(imageRef.id);
            t.set(bookmarkRef, {
                imageId: imageRef.id,
                imageUrl,
                prompt,
                aspectRatio,
                createdAt: FieldValue.serverTimestamp(),
                _autoGenerated: true,
                _type: 'discord_upscale'
            });

            logger.info(`[DiscordSync] Registered upscale: ${imageRef.id} for user: ${targetUserId}`);
            return { success: true, imageId: imageRef.id };
        });
    } catch (error: any) {
        if (error instanceof HttpsError) throw error;
        throw new HttpsError('internal', error.message);
    }
}
