import { logger, getS3Client, retryOperation } from "../lib/utils.js";
import { Billing } from "../lib/billing.js";
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { VertexAI, HarmCategory, HarmBlockThreshold } from "@google-cloud/vertexai";
import { B2_BUCKET, B2_PUBLIC_URL } from "../lib/constants.js";
import { PutObjectCommand } from "@aws-sdk/client-s3";
import { db, FieldValue } from "../firebaseInit.js";
import { HttpsError } from "firebase-functions/v2/https";
import { RequestWithAuth } from "../types/functions.js";
import { ensureUserExists } from "../lib/user.js";

import {
    MOCKUP_ITEMS, MOCKUP_PRESETS,
    TCG_ITEMS, TCG_PRESETS,
    DOLL_ITEMS, DOLL_PRESETS,
    RESKIN_ITEMS, RESKIN_PRESETS
} from "../lib/mockupData.js";

export {
    MOCKUP_ITEMS, MOCKUP_PRESETS,
    TCG_ITEMS, TCG_PRESETS,
    DOLL_ITEMS, DOLL_PRESETS,
    RESKIN_ITEMS, RESKIN_PRESETS
};

// ESM __dirname fix
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Initialize Vertex AI
const project = process.env.GCLOUD_PROJECT || "dreambees-alchemist";
const location = "us-central1";
const vertexAI = new VertexAI({ project, location });

/**
 * Generates a mockup using Vertex AI Imagen and uploads to B2
 */
async function generateSingleMockup(base64Image: string, item: any, preset: any, uid: string, source: string = 'vertex-ai', requestId?: string): Promise<string> {
    const generativeModel = vertexAI.getGenerativeModel({
        model: "image-generation-006",
    });

    const prompt = preset.prompt.replace('{subject}', item.formatSpec);

    logger.info(`[Mockup] Generating ${item.label} for ${uid}...`, { requestId });

    const response = await generativeModel.generateContent({
        contents: [{
            role: "user",
            parts: [
                { text: prompt },
                { inlineData: { mimeType: "image/png", data: base64Image } }
            ]
        }],
        safetySettings: [
            { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
            { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
            { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
            { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
        ]
    });

    const result = response.response;
    const candidates = result.candidates;
    if (!candidates || candidates.length === 0) {
        throw new Error("No image generated by Vertex AI.");
    }

    const generatedImageBase64 = candidates[0].content.parts[0].inlineData?.data;
    if (!generatedImageBase64) {
        throw new Error("Failed to extract image data from Vertex AI response.");
    }

    // Upload to B2
    const s3 = await getS3Client();
    const key = `mockups/${uid}/${Date.now()}_${item.id}.png`;

    const buffer = Buffer.from(generatedImageBase64, 'base64');

    await s3.send(new PutObjectCommand({
        Bucket: B2_BUCKET,
        Key: key,
        Body: buffer,
        ContentType: 'image/png'
    }));

    const url = `${B2_PUBLIC_URL}/${key}`;

    // 1. Log to private user collection
    await db.collection('generated_mockups').add({
        uid,
        itemId: item.id,
        presetId: preset.id,
        url,
        createdAt: FieldValue.serverTimestamp(),
        source: source,
        requestId: requestId || null
    });

    // 2. Add to public community feed
    await db.collection('mockups').add({
        userId: uid,
        mockupItemId: item.id,
        presetId: preset.id,
        imageUrl: url,
        thumbnailUrl: url,
        prompt: preset.prompt.replace('{subject}', item.formatSpec),
        isPublic: true,
        createdAt: FieldValue.serverTimestamp(),
        source: source,
        requestId: requestId || null,
        _type: 'discord_mockup'
    });

    return url;
}

/**
 * Generates a 2x2 Grid of Mockups (1 item, 4 presets)
 */
export const handleGenerateMockupGrid = async (request: RequestWithAuth<{ image: string, itemId: string, presetIds: string[], targetUserId?: string, targetDisplayName?: string, targetPhotoURL?: string, requestId?: string }>) => {
    const { image, itemId, presetIds, targetUserId, targetDisplayName, targetPhotoURL } = request.data;
    const uid = request.auth?.uid;
    const callerRole = (request.auth as any).token?.role || 'user';
    const finalUid = (['admin', 'system'].includes(callerRole) && targetUserId) ? targetUserId : uid;

    if (!finalUid) throw new HttpsError('unauthenticated', "User must be authenticated.");
    
    // Ensure user exists (JIT Provisioning)
    await ensureUserExists(finalUid, targetDisplayName, targetPhotoURL);

    const requestId = request.data.requestId || `grid_${Date.now()}`;

    return await Billing.runAsync(finalUid, 'MOCKUP_GRID', requestId, { itemId, presetIds }, async () => {
        const base64Data = image.replace(/^data:image\/\w+;base64,/, "");
        const item = MOCKUP_ITEMS.find(i => i.id === itemId) || TCG_ITEMS.find(i => i.id === itemId);
        if (!item) throw new Error("Item not found");

        const source = (['admin', 'system'].includes(callerRole)) ? 'discord_grid' : 'web_grid';

        const tasks = presetIds.slice(0, 4).map(async (pId) => {
            const preset = MOCKUP_PRESETS.find(p => p.id === pId) || TCG_PRESETS.find(p => p.id === pId) || MOCKUP_PRESETS[0];
            return generateSingleMockup(base64Data, item, preset, finalUid, source, requestId);
        });

        const urls = await Promise.all(tasks);
        return { urls, item };
    });
};

/**
 * Handles multiple mockup generations
 */
export const handleGenerateMockup = async (request: RequestWithAuth<{ image: string, items: string[], presetId?: string, requestId?: string }>) => {
    const { image, items, presetId } = request.data;
    const uid = request.auth?.uid;

    if (!uid) {
        throw new HttpsError('unauthenticated', "User must be authenticated.");
    }
    if (!image) {
        throw new Error("No image data provided.");
    }

    const requestId = request.data.requestId || `bulk_${Date.now()}`;

    return await Billing.runAsync(uid, 'MOCKUP_BULK', requestId, { itemCount: items.length }, async () => {
        const base64Data = image.replace(/^data:image\/\w+;base64,/, "");
        const results = [];

        for (const itemId of items) {
            const item = MOCKUP_ITEMS.find(i => i.id === itemId) ||
                TCG_ITEMS.find(i => i.id === itemId) ||
                DOLL_ITEMS.find(i => i.id === itemId) ||
                RESKIN_ITEMS.find(i => i.id === itemId);

            if (item) {
                let preset: any = null;
                if (presetId) {
                    preset = MOCKUP_PRESETS.find(p => p.id === presetId) ||
                        TCG_PRESETS.find(p => p.id === presetId) ||
                        DOLL_PRESETS.find(p => p.id === presetId) ||
                        RESKIN_PRESETS.find(p => p.id === presetId);
                }
                if (!preset) {
                    preset = MOCKUP_PRESETS.find(p => p.id === 'studio') || MOCKUP_PRESETS[0];
                }

                try {
                    const url = await generateSingleMockup(base64Data, item, preset, uid);
                    results.push({ itemId, url, success: true });
                } catch (err: any) {
                    logger.error(`[Mockup] Failed to generate ${itemId}:`, err);
                    results.push({ itemId, error: err.message, success: false });
                }
            }
        }

        return { results };
    });
};

/**
 * Handles Gacha Spin for Random Mockup
 */
export const handleGachaSpin = async (request: RequestWithAuth<{ image: string, category?: string, targetUserId?: string, targetDisplayName?: string, targetPhotoURL?: string, requestId?: string }>) => {
    const { image, category, targetUserId, targetDisplayName, targetPhotoURL } = request.data;
    const uid = request.auth?.uid; // Define uid here
    const callerRole = (request.auth as any).token?.role || 'user';

    // Allow system/admin to submit on behalf of a specific user
    const finalUid = (['admin', 'system'].includes(callerRole) && targetUserId) ? targetUserId : uid;

    if (!finalUid) {
        throw new HttpsError('unauthenticated', "User must be authenticated.");
    }

    // Ensure user exists (JIT Provisioning)
    await ensureUserExists(finalUid, targetDisplayName, targetPhotoURL);

    const requestId = request.data.requestId || `gacha_${Date.now()}`;

    return await Billing.runAsync(finalUid, 'MOCKUP_GACHA', requestId, { category }, async () => {
        const base64Data = image.replace(/^data:image\/\w+;base64,/, "");

        // Pick random item and preset
        let pool = [...MOCKUP_ITEMS, ...TCG_ITEMS, ...DOLL_ITEMS, ...RESKIN_ITEMS];
        if (category) {
            pool = pool.filter(i => i.category === category);
        }

        const item = pool[Math.floor(Math.random() * pool.length)];
        const presetPool = [...MOCKUP_PRESETS, ...TCG_PRESETS, ...DOLL_PRESETS, ...RESKIN_PRESETS];
        const preset = presetPool[Math.floor(Math.random() * presetPool.length)];

        // Determine source
        const source = (['admin', 'system'].includes(callerRole)) ? 'discord_gacha' : 'web_gacha';

        const url = await generateSingleMockup(base64Data, item, preset, finalUid, source, requestId);

        return {
            url,
            item: { id: item.id, label: item.label },
            preset: { id: preset.id, label: preset.label }
        };
    });
};

/**
 * Generates a specific Mockup Item with a Preset
 */
export const handleGenerateMockupItem = async (request: RequestWithAuth<{ image: string, itemId: string, presetId?: string, targetUserId?: string, targetDisplayName?: string, targetPhotoURL?: string, requestId?: string }>) => {
    const { image, itemId, presetId, targetUserId, targetDisplayName, targetPhotoURL } = request.data;
    const uid = request.auth?.uid;
    const callerRole = (request.auth as any).token?.role || 'user';

    // Allow system/admin to submit on behalf of a specific user for Discord sync
    const finalUid = (['admin', 'system'].includes(callerRole) && targetUserId) ? targetUserId : uid;
    
    if (!finalUid) {
        throw new HttpsError('unauthenticated', "User must be authenticated.");
    }

    // Ensure user exists (JIT Provisioning)
    await ensureUserExists(finalUid, targetDisplayName, targetPhotoURL);

    if (!image) {
        throw new Error("No image data provided.");
    }
    if (!itemId) {
        throw new Error("No item ID provided.");
    }

    const item = MOCKUP_ITEMS.find(i => i.id === itemId) ||
        TCG_ITEMS.find(i => i.id === itemId) ||
        DOLL_ITEMS.find(i => i.id === itemId) ||
        RESKIN_ITEMS.find(i => i.id === itemId);

    if (!item) {
        throw new HttpsError('not-found', `Mockup Item '${itemId}' not found in backend config.`);
    }

    let preset: any = null;
    if (presetId) {
        preset = MOCKUP_PRESETS.find(p => p.id === presetId) ||
            TCG_PRESETS.find(p => p.id === presetId) ||
            DOLL_PRESETS.find(p => p.id === presetId) ||
            RESKIN_PRESETS.find(p => p.id === presetId);
    }
    if (!preset) {
        preset = MOCKUP_PRESETS.find(p => p.id === 'studio') || MOCKUP_PRESETS[0];
    }

    const requestId = request.data.requestId || `mockitem_${Date.now()}`;

    return await Billing.runAsync(finalUid, 'MOCKUP_GEN', requestId, { type: 'mockup_item', itemId, presetId }, async () => {
        const base64Data = image.replace(/^data:image\/\w+;base64,/, "");

        // Determine source for better tracking
        const source = (['admin', 'system'].includes(callerRole)) ? 'discord' : 'web';

        const result = await generateSingleMockup(base64Data, item, preset, finalUid, source, requestId);

        return { url: result, item, preset };
    });
};
