/* global process */
import fetch from 'node-fetch';

async function testGalmixUnauthenticated() {
    console.log("Testing GalMix unauthenticated generation request...");

    // This assumes the function is running locally or at a known URL
    const functionUrl = process.env.GENERATE_API_URL || "http://localhost:5001/dreambees-alchemist/us-central1/api";

    const payload = {
        data: {
            action: 'createGenerationRequest',
            prompt: "A test image generated by GalMix, high quality, cinematic",
            modelId: 'galmix',
            aspectRatio: '1:1',
            steps: 20
        }
    };

    try {
        const response = await fetch(functionUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        const result = await response.json();

        if (response.ok) {
            console.log("✓ Successfully created generation request!");
            console.log("Request ID:", result.result?.requestId);
        } else {
            console.error("✗ Failed to create request:", result.error || result);
        }
    } catch (err) {
        console.error("✗ Error calling function:", err.message);
    }
}

testGalmixUnauthenticated();
